version: '3.9'
services:
  ibnuapp:
    image: francescoxx/laravelapp:1.0.3
    container_name: ibnuapp
    build: .
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    container_name: db
    environment:
      POSTGRES_DB: ibnu-app
      POSTGRES_USER: ibnufaisal
      POSTGRES_PASSWORD: secret
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: {}